# -*- coding: utf-8 -*-
"""Untitled71.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cA7X3hXCr5qTfKSTx1MzRhQWUDt6XBcW

1. Regression analysis
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense


df= pd.read_excel("/content/dataset.xlsx")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor


df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")

df = df.replace([np.inf, -np.inf], np.nan)


targets = ["CropYield_T", "SOC_RR", "GWP_RR"]
targets = [t for t in targets if t in df.columns]


X = df.drop(columns=targets, errors="ignore")
y = df[targets]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns


num_imputer = SimpleImputer(strategy="median")
X[num_cols] = num_imputer.fit_transform(X[num_cols])

=
cat_imputer = SimpleImputer(strategy="most_frequent")
X[cat_cols] = cat_imputer.fit_transform(X[cat_cols])


le = LabelEncoder()
for col in cat_cols:
    X[col] = le.fit_transform(X[col].astype(str))


y_imputer = SimpleImputer(strategy="median")
y = pd.DataFrame(y_imputer.fit_transform(y), columns=y.columns)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


model = MultiOutputRegressor(
    RandomForestRegressor(n_estimators=200, random_state=42)
)

model.fit(X_train, y_train)
pred = model.predict(X_test)


from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

print("\n RESULTS")
print("R2:", r2_score(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))
print("MAE:", mean_absolute_error(y_test, pred))

"""2. "Linear Regression": MultiOutputRegressor(LinearRegression()),
    "Ridge Regression": MultiOutputRegressor(Ridge(alpha=1.0)),
    "Random Forest": MultiOutputRegressor(RandomForestRegressor(n_estimators=200)),
    "Extra Trees": MultiOutputRegressor(ExtraTreesRegressor(n_estimators=200)),
    "SVR": MultiOutputRegressor(SVR()),
    "XGBoost": MultiOutputRegressor(XGBRegressor(n_estimators=200, learning_rate=0.05)),
    "LightGBM": MultiOutputRegressor(LGBMRegressor(n_estimators=200, learning_rate=0.05)),
    "MLP Neural Net": MultiOutputRegressor(MLPRegressor(hidden_layer_sizes=(100,50), max_iter=500))
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

from sklearn.multioutput import MultiOutputRegressor

from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor


df = pd.read_excel("/content/dataset.xlsx")


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


targets = ["CropYield_T", "SOC_RR", "GWP_RR"]
targets = [t for t in targets if t in df.columns]

X = df.drop(columns=targets, errors="ignore")
y = df[targets]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

X[num_cols] = num_imputer.fit_transform(X[num_cols])
X[cat_cols] = cat_imputer.fit_transform(X[cat_cols])

le = LabelEncoder()
for col in cat_cols:
    X[col] = le.fit_transform(X[col].astype(str))

y = SimpleImputer(strategy="median").fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


models = {
    "Linear Regression": MultiOutputRegressor(LinearRegression()),
    "Ridge Regression": MultiOutputRegressor(Ridge(alpha=1.0)),
    "Random Forest": MultiOutputRegressor(RandomForestRegressor(n_estimators=200)),
    "Extra Trees": MultiOutputRegressor(ExtraTreesRegressor(n_estimators=200)),
    "SVR": MultiOutputRegressor(SVR()),
    "XGBoost": MultiOutputRegressor(XGBRegressor(n_estimators=200, learning_rate=0.05)),
    "LightGBM": MultiOutputRegressor(LGBMRegressor(n_estimators=200, learning_rate=0.05)),
    "MLP Neural Net": MultiOutputRegressor(MLPRegressor(hidden_layer_sizes=(100,50), max_iter=500))
}


results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    r2 = r2_score(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    mae = mean_absolute_error(y_test, pred)

    results.append([name, r2, rmse, mae])

    print("\n====================")
    print("Model:", name)
    print("R2:", r2)
    print("RMSE:", rmse)
    print("MAE:", mae)

=
results_df = pd.DataFrame(results, columns=["Model", "R2", "RMSE", "MAE"])
results_df = results_df.sort_values("R2", ascending=False)

print("\n🏆 FINAL MODEL COMPARISON TABLE")
print(results_df)



"""3. visualization"""

import matplotlib.pyplot as plt
import numpy as np


models = [
    "Random Forest", "Extra Trees", "LightGBM", "XGBoost",
    "Ridge Regression", "Linear Regression", "MLP Neural Network", "SVR"
]


r2 = [0.971, 0.9337, 0.9049, 0.8753, 0.8546, 0.8545, 0.7032, 0.4697]
rmse = [1.3506, 1.1186, 1.4303, 1.2874, 2.2535, 2.2586, 1.4192, 7.305]
mae = [0.1545, 0.1302, 0.2429, 0.1636, 0.6592, 0.6631, 0.4822, 1.4432]

x = np.arange(len(models))
width = 0.25


plt.figure(figsize=(14,6))

plt.bar(x - width, r2, width, label='R² Score')
plt.bar(x, rmse, width, label='RMSE')
plt.bar(x + width, mae, width, label='MAE')

plt.xticks(x, models, rotation=45, ha='right')
plt.ylabel("Metric Value")
plt.title("Model Comparison - R², RMSE, MAE")
plt.legend()
plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns

data = pd.DataFrame({
    "Model": models,
    "R2": r2,
    "RMSE": rmse,
    "MAE": mae
}).set_index("Model")

plt.figure(figsize=(8,5))
sns.heatmap(data, annot=True, cmap="YlGnBu", fmt=".3f")
plt.title("Model Performance Comparison Heatmap")
plt.show()

"""4. Multi model regression"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor



df = pd.read_excel("/content/dataset.xlsx")

df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


targets = ["CropYield_T", "SOC_RR", "GWP_RR"]
targets = [t for t in targets if t in df.columns]


X = df.drop(columns=targets, errors="ignore")
y = df[targets]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

X[num_cols] = SimpleImputer(strategy="median").fit_transform(X[num_cols])
X[cat_cols] = SimpleImputer(strategy="most_frequent").fit_transform(X[cat_cols])


le = LabelEncoder()
for col in cat_cols:
    X[col] = le.fit_transform(X[col].astype(str))


y = pd.DataFrame(SimpleImputer(strategy="median").fit_transform(y), columns=y.columns)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(),
    "Lasso Regression": Lasso(),
    "ElasticNet": ElasticNet(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(n_estimators=200, random_state=42),
    "Extra Trees": ExtraTreesRegressor(n_estimators=200, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(),
    "XGBoost": XGBRegressor(n_estimators=300, learning_rate=0.05),
    "LightGBM": LGBMRegressor(n_estimators=300, learning_rate=0.05),
    "CatBoost": CatBoostRegressor(iterations=300, learning_rate=0.05, verbose=0),
    "SVR": SVR(),
    "KNN": KNeighborsRegressor()
}


results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    r2 = r2_score(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    mae = mean_absolute_error(y_test, pred)

    results.append([name, r2, rmse, mae])

    print("\n=========================")
    print("Model:", name)
    print("R2:", r2)
    print("RMSE:", rmse)
    print("MAE:", mae)


results_df = pd.DataFrame(results, columns=["Model", "R2", "RMSE", "MAE"])
results_df = results_df.sort_values(by="R2", ascending=False)

print("\n FINAL MODEL COMPARISON")
print(results_df)

/content/dataset.xlsx

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

df = pd.read_excel("/content/dataset.xlsx")


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


targets = ["CropYield_T", "SOC_RR", "GWP_RR"]
targets = [t for t in targets if t in df.columns]


X = df.drop(columns=targets, errors="ignore")
y = df[targets]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

X[num_cols] = SimpleImputer(strategy="median").fit_transform(X[num_cols])
X[cat_cols] = SimpleImputer(strategy="most_frequent").fit_transform(X[cat_cols])


le = LabelEncoder()
for col in cat_cols:
    X[col] = le.fit_transform(X[col].astype(str))


y = pd.DataFrame(SimpleImputer(strategy="median").fit_transform(y), columns=y.columns)



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(),
    "Lasso Regression": Lasso(),
    "ElasticNet": ElasticNet(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(n_estimators=200, random_state=42),
    "Extra Trees": ExtraTreesRegressor(n_estimators=200, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(),
    "XGBoost": XGBRegressor(n_estimators=300, learning_rate=0.05),
    "LightGBM": LGBMRegressor(n_estimators=300, learning_rate=0.05),

    "SVR": SVR(),
    "KNN": KNeighborsRegressor()
}


results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    r2 = r2_score(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    mae = mean_absolute_error(y_test, pred)

    results.append([name, r2, rmse, mae])

    print("\n=========================")
    print("🌾 Model:", name)
    print("R2:", r2)
    print("RMSE:", rmse)
    print("MAE:", mae)


results_df = pd.DataFrame(results, columns=["Model", "R2", "RMSE", "MAE"])
results_df = results_df.sort_values(by="R2", ascending=False)

print("\n🏆 FINAL MODEL COMPARISON")
print(results_df)



"""5. correlation"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd


plt.figure(figsize=(12,8))
sns.heatmap(df.select_dtypes(include=np.number).corr(), cmap="coolwarm", center=0)
plt.title("Correlation Heatmap")
plt.show()

plt.figure()
sns.histplot(df["CropYield_T"], kde=True)
plt.title("Crop Yield Distribution")
plt.show()


plt.figure()
sns.boxplot(x="Type_biochar", y="CropYield_T", data=df)
plt.xticks(rotation=45)
plt.title("Biochar Type vs Crop Yield")
plt.show()


plt.figure()
sns.boxplot(data=df[["SOC_CK", "SOC_T"]])
plt.title("SOC: Control vs Treatment")
plt.show()


plt.figure()
sns.scatterplot(x="Temperature", y="GWP_RR", data=df)
plt.title("Temperature vs GWP Response Ratio")
plt.show()


plt.figure()
sns.scatterplot(x="BiocharAddition", y="CropYield_T", data=df)
plt.title("Biochar Addition vs Crop Yield")
plt.show()


from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

num_df = df.select_dtypes(include=np.number).dropna()
scaled = StandardScaler().fit_transform(num_df)

pca = PCA(n_components=2)
pca_result = pca.fit_transform(scaled)

plt.figure()
plt.scatter(pca_result[:,0], pca_result[:,1])
plt.title("PCA Visualization of Dataset Structure")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()





import matplotlib.pyplot as plt
import seaborn as sns

top_types = df["Type_biochar"].value_counts().nlargest(10).index
df_top = df[df["Type_biochar"].isin(top_types)]

order = df_top.groupby("Type_biochar")["CropYield_T"].mean().sort_values(ascending=False).index

plt.figure(figsize=(12,6))

sns.barplot(
    data=df_top,
    x="Type_biochar",
    y="CropYield_T",
    order=order,
    estimator="mean",
    errorbar="sd",
    palette="viridis"
)

plt.xticks(rotation=45, ha="right")
plt.title("Average Crop Yield by Biochar Type (Top 10)")
plt.ylabel("Mean Crop Yield")
plt.xlabel("Biochar Type")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

top_types = df["Type_biochar"].value_counts().nlargest(10).index
df_top = df[df["Type_biochar"].isin(top_types)]

order = df_top.groupby("Type_biochar")["CropYield_T"].median().sort_values(ascending=False).index

plt.figure(figsize=(12,6))

sns.boxplot(
    data=df_top,
    x="Type_biochar",
    y="CropYield_T",
    order=order,
    palette="viridis"
)

plt.xticks(rotation=45, ha="right")
plt.title(" Biochar vs Crop Yield (Best Scientific View)")
plt.xlabel("Biochar Type")
plt.ylabel("Crop Yield")
plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler


df.columns = df.columns.str.strip().str.replace(" ", "_")


metrics = [
    "CropYield_T",
    "CropYield_CK",
    "SOC_RR",
    "TN_RR",
    "CO2_RR",
    "CH4_RR",
    "N2O_RR",
    "GWP_RR",
    "GHGI_RR"
]

metrics = [m for m in metrics if m in df.columns]


bio = df.groupby("Type_biochar")[metrics].mean()


scaler = MinMaxScaler()
bio_scaled = pd.DataFrame(
    scaler.fit_transform(bio),
    index=bio.index,
    columns=bio.columns
)


plt.figure(figsize=(12,6))

sns.heatmap(
    bio_scaled,
    cmap="YlGnBu",
    linewidths=0.5
)

plt.title("Overall Biochar Performance Across All Categories (Normalized)")
plt.xlabel("Metrics")
plt.ylabel("Biochar Type")

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler


df.columns = df.columns.str.strip().str.replace(" ", "_")

metrics = [
    "CropYield_T",
    "SOC_RR",
    "TN_RR",
    "CO2_RR",
    "CH4_RR",
    "N2O_RR",
    "GWP_RR",
    "GHGI_RR"
]

metrics = [m for m in metrics if m in df.columns]


bio = df.groupby("Type_biochar")[metrics].mean()


scaler = MinMaxScaler()
bio_norm = pd.DataFrame(
    scaler.fit_transform(bio),
    index=bio.index,
    columns=bio.columns
)


top_bio = bio_norm.mean(axis=1).sort_values(ascending=False).head(8)
bio_plot = bio_norm.loc[top_bio.index]


plt.figure(figsize=(14,6))

bio_plot.plot(kind="bar", figsize=(14,6), colormap="viridis")

plt.title(" Multi-Metric Biochar Performance Comparison (Normalized)")
plt.ylabel("Normalized Score (0–1)")
plt.xlabel("Biochar Type")
plt.xticks(rotation=45, ha="right")
plt.legend(title="Metrics", bbox_to_anchor=(1.02, 1))
plt.tight_layout()

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler


df.columns = df.columns.str.strip().str.replace(" ", "_")

metrics = [
    "CropYield_T",
    "SOC_RR",
    "TN_RR",
    "CO2_RR",
    "CH4_RR",
    "N2O_RR",
    "GWP_RR",
    "GHGI_RR"
]

metrics = [m for m in metrics if m in df.columns]


bio = df.groupby("Type_biochar")[metrics].mean()


scaler = MinMaxScaler()
bio_norm = pd.DataFrame(
    scaler.fit_transform(bio),
    index=bio.index,
    columns=bio.columns
)


bio_norm["Final_Score"] = bio_norm.mean(axis=1)

best_biochar = bio_norm["Final_Score"].idxmax()


print("\n BEST BIOCHAR OVERALL:", best_biochar)


top_bio = bio_norm["Final_Score"].sort_values(ascending=False).head(8).index
bio_plot = bio_norm.loc[top_bio].drop(columns=["Final_Score"])


plt.figure(figsize=(14,6))

bio_plot.plot(kind="bar", colormap="viridis")

plt.title(" Multi-Metric Biochar Performance (Normalized)")
plt.ylabel("Score (0–1)")
plt.xlabel("Biochar Type")
plt.xticks(rotation=45, ha="right")
plt.legend(title="Metrics", bbox_to_anchor=(1.02, 1))
plt.tight_layout()

plt.show()

import pandas as pd
from sklearn.preprocessing import MinMaxScaler


df.columns = df.columns.str.strip().str.replace(" ", "_")


bio = df.groupby("Type_biochar").mean(numeric_only=True)


yield_score = bio["CropYield_T"]
best_yield = yield_score.idxmax()


soil_cols = [c for c in ["SOC_RR", "TN_RR"] if c in bio.columns]
soil_score = bio[soil_cols].sum(axis=1)
best_soil = soil_score.idxmax()


em_cols = [c for c in ["CO2_RR", "CH4_RR", "N2O_RR"] if c in bio.columns]
emission_score = -bio[em_cols].sum(axis=1)
best_emission = emission_score.idxmax()


clim_cols = [c for c in ["GWP_RR", "GHGI_RR"] if c in bio.columns]
climate_score = -bio[clim_cols].sum(axis=1)
best_climate = climate_score.idxmax()


print("\n BEST BIOCHAR BY CATEGORY")
print("--------------------------------")

print("Yield Best Biochar      :", best_yield)
print(" Soil Best Biochar       :", best_soil)
print(" Emission Best Biochar   :", best_emission)
print(" Climate Best Biochar    :", best_climate)

import pandas as pd
from sklearn.preprocessing import MinMaxScaler


df.columns = df.columns.str.strip().str.replace(" ", "_")


bio = df.groupby("Type_biochar").mean(numeric_only=True)

metrics = [
    "CropYield_T",
    "SOC_RR",
    "TN_RR",
    "CO2_RR",
    "CH4_RR",
    "N2O_RR",
    "GWP_RR",
    "GHGI_RR"
]

metrics = [m for m in metrics if m in bio.columns]

bio = bio[metrics]


scaler = MinMaxScaler()
bio_norm = pd.DataFrame(
    scaler.fit_transform(bio),
    index=bio.index,
    columns=bio.columns
)


bio_norm["Final_Score"] = bio_norm.mean(axis=1)


top10 = bio_norm.sort_values("Final_Score", ascending=False).head(10)

print("\n TOP 10 BIOCHAR TYPES")
print(top10["Final_Score"])

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

top10["Final_Score"].plot(kind="bar", color="green")

plt.title("Top 10 Biochar Types (Overall Score)")
plt.ylabel("Composite Performance Score")
plt.xlabel("Biochar Type")
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()



import matplotlib.pyplot as plt
import seaborn as sns


top_types = df["Type_biochar"].value_counts().nlargest(10).index

df_top = df[df["Type_biochar"].isin(top_types)]


order = df_top.groupby("Type_biochar")["CropYield_T"].median().sort_values(ascending=False).index


plt.figure(figsize=(12,6))

sns.boxplot(
    data=df_top,
    x="CropYield_T",
    y="Type_biochar",
    order=order,
    palette="viridis"
)


sns.pointplot(
    data=df_top,
    x="CropYield_T",
    y="Type_biochar",
    order=order,
    color="red",
    errorbar=None
)

plt.title("Top 10 Biochar Types vs Crop Yield (Ranked)", fontsize=14)
plt.xlabel("Crop Yield")
plt.ylabel("Biochar Type")

plt.grid(axis="x", linestyle="--", alpha=0.3)
plt.tight_layout()
plt.show()







import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np


target = "CropYield_T"


corr = df.select_dtypes(include=np.number).corr()[target].sort_values(ascending=False)


top_features = list(corr.head(10).index) + list(corr.tail(10).index)

plt.figure(figsize=(10,6))
sns.heatmap(df[top_features].corr(), annot=False, cmap="coolwarm", center=0)
plt.title("Top Feature Correlation Heatmap (Focused View)")
plt.show()



import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from xgboost import XGBClassifier

import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_excel("/content/dataset.xlsx")

df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)



df = df.dropna(subset=["CropYield_T"])

df["Yield_Class"] = pd.qcut(
    df["CropYield_T"],
    q=3,
    labels=["Low", "Medium", "High"]
)


X = df.drop(columns=["CropYield_T", "Yield_Class"], errors="ignore")
y = df["Yield_Class"]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

X[num_cols] = SimpleImputer(strategy="median").fit_transform(X[num_cols])
X[cat_cols] = SimpleImputer(strategy="most_frequent").fit_transform(X[cat_cols])


le = LabelEncoder()
for col in cat_cols:
    X[col] = le.fit_transform(X[col].astype(str))

y = LabelEncoder().fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)
log_pred = log_model.predict(X_test)

print("\n LOGISTIC REGRESSION")
print("Accuracy:", accuracy_score(y_test, log_pred))
print(classification_report(y_test, log_pred))


rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

print("\n RANDOM FOREST")
print("Accuracy:", accuracy_score(y_test, rf_pred))
print(classification_report(y_test, rf_pred))


xgb_model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    eval_metric="mlogloss"
)

xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

print("\n XGBOOST")
print("Accuracy:", accuracy_score(y_test, xgb_pred))
print(classification_report(y_test, xgb_pred))


plt.figure(figsize=(5,4))
sns.heatmap(confusion_matrix(y_test, rf_pred), annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix - Random Forest")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

from lightgbm import LGBMClassifier


from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd


df = pd.read_excel("/content/dataset.xlsx")
df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


df = df.dropna(subset=["CropYield_T"])

df["Yield_Class"] = pd.qcut(
    df["CropYield_T"],
    q=3,
    labels=["Low", "Medium", "High"]
)


X = df.drop(columns=["CropYield_T", "Yield_Class"], errors="ignore")
y = df["Yield_Class"]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

X[num_cols] = SimpleImputer(strategy="median").fit_transform(X[num_cols])
X[cat_cols] = SimpleImputer(strategy="most_frequent").fit_transform(X[cat_cols])


for col in cat_cols:
    X[col] = LabelEncoder().fit_transform(X[col].astype(str))


y = LabelEncoder().fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


models = {
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "Extra Trees": ExtraTreesClassifier(n_estimators=200, random_state=42),
    "LightGBM": LGBMClassifier(n_estimators=200, learning_rate=0.05),

}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    results[name] = acc

    print(f"\n{name}")
    print("Accuracy:", acc)
    print(classification_report(y_test, pred))



best_model = max(models.items(), key=lambda x: results[x[0]])[1]

if hasattr(best_model, "feature_importances_"):
    imp = pd.Series(best_model.feature_importances_, index=X.columns).sort_values(ascending=False).head(15)

    plt.figure(figsize=(8,5))
    sns.barplot(x=imp.values, y=imp.index)
    plt.title("Top Features Affecting Yield Class")
    plt.show()



X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(6,5))
plt.scatter(X_pca[:,0], X_pca[:,1], c=y, cmap="viridis", alpha=0.6)
plt.title("PCA: Yield Class Separation")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()


top_types = df["Type_biochar"].value_counts().nlargest(10).index
df_top = df[df["Type_biochar"].isin(top_types)]

groups = [
    df_top[df_top["Type_biochar"] == t]["CropYield_T"].dropna()
    for t in top_types
]

f_stat, p_val = f_oneway(*groups)

print("\n ANOVA TEST")
print("F-stat:", f_stat)
print("p-value:", p_val)


tukey = pairwise_tukeyhsd(
    endog=df_top["CropYield_T"],
    groups=df_top["Type_biochar"],
    alpha=0.05
)

print("\n TUKEY TEST RESULTS")
print(tukey)


corr = df.select_dtypes(include=np.number).corr()["CropYield_T"].sort_values()

plt.figure(figsize=(6,10))
sns.heatmap(corr.to_frame(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation with Crop Yield")
plt.show()

"""8. Classificaiton"""

!pip install catboost

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd


df = pd.read_excel("/content/dataset.xlsx")
df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


df = df.dropna(subset=["CropYield_T"])

df["Yield_Class"] = pd.qcut(
    df["CropYield_T"],
    q=3,
    labels=["Low", "Medium", "High"]
)


X = df.drop(columns=["CropYield_T", "Yield_Class"], errors="ignore")
y = df["Yield_Class"]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

X[num_cols] = SimpleImputer(strategy="median").fit_transform(X[num_cols])
X[cat_cols] = SimpleImputer(strategy="most_frequent").fit_transform(X[cat_cols])


for col in cat_cols:
    X[col] = LabelEncoder().fit_transform(X[col].astype(str))


y = LabelEncoder().fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


models = {
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "Extra Trees": ExtraTreesClassifier(n_estimators=200, random_state=42),
    "LightGBM": LGBMClassifier(n_estimators=200, learning_rate=0.05),
    "CatBoost": CatBoostClassifier(iterations=200, learning_rate=0.05, verbose=0)
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    results[name] = acc

    print(f"\n {name}")
    print("Accuracy:", acc)
    print(classification_report(y_test, pred))


best_model = max(models.items(), key=lambda x: results[x[0]])[1]

if hasattr(best_model, "feature_importances_"):
    imp = pd.Series(best_model.feature_importances_, index=X.columns).sort_values(ascending=False).head(15)

    plt.figure(figsize=(8,5))
    sns.barplot(x=imp.values, y=imp.index)
    plt.title("Top Features Affecting Yield Class")
    plt.show()


X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(6,5))
plt.scatter(X_pca[:,0], X_pca[:,1], c=y, cmap="viridis", alpha=0.6)
plt.title("PCA: Yield Class Separation")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()


top_types = df["Type_biochar"].value_counts().nlargest(10).index
df_top = df[df["Type_biochar"].isin(top_types)]

groups = [
    df_top[df_top["Type_biochar"] == t]["CropYield_T"].dropna()
    for t in top_types
]

f_stat, p_val = f_oneway(*groups)

print("\n ANOVA TEST")
print("F-stat:", f_stat)
print("p-value:", p_val)

tukey = pairwise_tukeyhsd(
    endog=df_top["CropYield_T"],
    groups=df_top["Type_biochar"],
    alpha=0.05
)

print("\nTUKEY TEST RESULTS")
print(tukey)


corr = df.select_dtypes(include=np.number).corr()["CropYield_T"].sort_values()

plt.figure(figsize=(6,10))
sns.heatmap(corr.to_frame(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation with Crop Yield")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


data = {
    "Task": [
        "SOIL HEALTH", "SOIL HEALTH", "SOIL HEALTH", "SOIL HEALTH", "SOIL HEALTH", "SOIL HEALTH",
        "ENV IMPACT", "ENV IMPACT", "ENV IMPACT", "ENV IMPACT", "ENV IMPACT", "ENV IMPACT",
        "BIOCHAR", "BIOCHAR", "BIOCHAR", "BIOCHAR", "BIOCHAR", "BIOCHAR",
        "CROP YIELD", "CROP YIELD", "CROP YIELD", "CROP YIELD", "CROP YIELD", "CROP YIELD"
    ],
    "Model": [
        "LR", "RF", "ET", "XGB", "LGBM", "CAT",
        "LR", "RF", "ET", "XGB", "LGBM", "CAT",
        "LR", "RF", "ET", "XGB", "LGBM", "CAT",
        "LR", "RF", "ET", "XGB", "LGBM", "CAT"
    ],
    "Accuracy": [
        0.818, 0.909, 0.864, 0.955, 0.955, 1.0,
        0.927, 0.927, 0.789, 0.982, 1.0, 1.0,
        0.849, 0.957, 0.856, 0.986, 1.0, 0.986,
        0.8237, 0.8816, 0.8665, 0.9597, 0.9572, 0.9421
    ],
    "Precision": [
        0.78, 0.94, 0.84, 0.93, 0.97, 1.0,
        0.93, 0.93, 0.79, 0.98, 1.0, 1.0,
        0.72, 0.95, 0.73, 0.96, 1.0, 0.96,
        0.82, 0.88, 0.87, 0.96, 0.96, 0.94
    ],
    "Recall": [
        0.82, 0.83, 0.80, 0.97, 0.92, 1.0,
        0.93, 0.93, 0.79, 0.98, 1.0, 1.0,
        0.71, 0.88, 0.64, 0.99, 1.0, 0.99,
        0.82, 0.88, 0.87, 0.96, 0.96, 0.94
    ],
    "F1-Score": [
        0.79, 0.87, 0.82, 0.95, 0.94, 1.0,
        0.93, 0.93, 0.79, 0.98, 1.0, 1.0,
        0.71, 0.91, 0.66, 0.97, 1.0, 0.97,
        0.82, 0.88, 0.87, 0.96, 0.96, 0.94
    ]
}

df = pd.DataFrame(data)


metrics = ["Accuracy", "Precision", "Recall", "F1-Score"]

for task in df["Task"].unique():
    temp = df[df["Task"] == task]

    temp.set_index("Model")[metrics].plot(kind="bar", figsize=(10, 5))
    plt.title(f"{task} - Model Comparison")
    plt.ylabel("Score")
    plt.ylim(0, 1.05)
    plt.xticks(rotation=45)
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.show()

plt.figure(figsize=(12, 6))
heatmap_data = df.pivot_table(index="Model", columns="Task", values="Accuracy")

sns.heatmap(heatmap_data, annot=True, cmap="YlGnBu")
plt.title("Accuracy Heatmap (Model vs Task)")
plt.show()


plt.figure(figsize=(10, 6))
model_avg = df.groupby("Model")[metrics].mean()

sns.heatmap(model_avg, annot=True, cmap="coolwarm")
plt.title("Average Model Performance Across All Tasks")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


df = df.dropna(subset=["Yield_Class", "CropYield_T"])


num_df = df.select_dtypes(include=np.number)
class_profile = df.groupby("Yield_Class")[num_df.columns].mean()

plt.figure(figsize=(12,6))
sns.heatmap(class_profile.T, cmap="coolwarm", center=0)
plt.title("Feature Patterns Across Yield Classes")
plt.show()


X = num_df.fillna(num_df.median())
X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(7,5))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=df["Yield_Class"], palette="viridis")
plt.title("PCA: Yield Class Separation")
plt.show()


plt.figure(figsize=(8,5))
sns.violinplot(x="Yield_Class", y="CropYield_T", data=df, palette="Set2")
plt.title("Yield Distribution Across Classes")
plt.show()


try:
    importances = model.feature_importances_
    feat_imp = pd.Series(importances, index=X.columns).sort_values(ascending=False).head(15)

    plt.figure(figsize=(8,5))
    sns.barplot(x=feat_imp.values, y=feat_imp.index)
    plt.title("Top Features Influencing Yield Class")
    plt.show()
except:
    print(" Model not defined for feature importance")


try:
    cm = confusion_matrix(y_test, pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()
except:
    print(" y_test / pred not defined")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier


df = pd.read_excel("/content/dataset.xlsx")


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


df = df.dropna(subset=["CropYield_RR", "SOC_RR"])

df["Biochar_Effective"] = np.where(
    (df["CropYield_RR"] > 1) & (df["SOC_RR"] > 1),
    "Effective",
    "Ineffective"
)


X = df.drop(columns=["Biochar_Effective", "CropYield_RR", "SOC_RR"], errors="ignore")
y = df["Biochar_Effective"]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

X[num_cols] = SimpleImputer(strategy="median").fit_transform(X[num_cols])
X[cat_cols] = SimpleImputer(strategy="most_frequent").fit_transform(X[cat_cols])

for col in cat_cols:
    X[col] = LabelEncoder().fit_transform(X[col].astype(str))


y = LabelEncoder().fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "Extra Trees": ExtraTreesClassifier(n_estimators=200, random_state=42),
    "XGBoost": XGBClassifier(n_estimators=300, learning_rate=0.05, eval_metric="logloss"),
    "LightGBM": LGBMClassifier(n_estimators=300, learning_rate=0.05),
    "CatBoost": CatBoostClassifier(iterations=300, learning_rate=0.05, verbose=0)
}

results = {}


for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)
    results[name] = acc

    print("\n==============================")
    print("", name)
    print("Accuracy:", acc)
    print(classification_report(y_test, pred))


best_model = max(results, key=results.get)
print("\nBest Model:", best_model, "Accuracy:", results[best_model])

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd



cm = confusion_matrix(y_test, pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix - Biochar Effectiveness")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()


X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(7,5))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=y, palette="viridis")
plt.title("PCA: Biochar Effectiveness Separation")
plt.show()


plt.figure(figsize=(5,4))
sns.countplot(x=y)
plt.title("Class Distribution (Effective vs Ineffective)")
plt.show()


try:
    importances = model.feature_importances_
    feat_imp = pd.Series(importances, index=X.columns).sort_values(ascending=False).head(15)

    plt.figure(figsize=(8,5))
    sns.barplot(x=feat_imp.values, y=feat_imp.index)
    plt.title("Top Features Driving Biochar Effectiveness")
    plt.show()
except:
    print("Feature importance not available for this model")


try:
    y_score = model.predict_proba(X_test)[:,1]

    fpr, tpr, _ = roc_curve(y_test, y_score)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(5,4))
    plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
    plt.plot([0,1], [0,1], linestyle="--")
    plt.title("ROC Curve - Biochar Effectiveness")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend()
    plt.show()

except:
    print("ROC not available for this model")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier


df = pd.read_excel("/content/dataset.xlsx")


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


df = df.dropna(subset=["CropYield_RR", "SOC_RR"])

df["Biochar_Effectiveness"] = np.where(
    (df["CropYield_RR"] > 1) & (df["SOC_RR"] > 1),
    "Effective",
    "Ineffective"
)


X = df.drop(columns=["Biochar_Effectiveness", "CropYield_RR", "SOC_RR"], errors="ignore")
y = df["Biochar_Effectiveness"]


num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

X_num = pd.DataFrame(num_imputer.fit_transform(X[num_cols]), columns=num_cols, index=X.index)
X_cat = pd.DataFrame(cat_imputer.fit_transform(X[cat_cols]), columns=cat_cols, index=X.index)

X = pd.concat([X_num, X_cat], axis=1)

for col in cat_cols:
    X[col] = LabelEncoder().fit_transform(X[col].astype(str))


y = LabelEncoder().fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=300, random_state=42),
    "Extra Trees": ExtraTreesClassifier(n_estimators=300, random_state=42),
    "XGBoost": XGBClassifier(n_estimators=300, learning_rate=0.05, eval_metric="logloss"),
    "LightGBM": LGBMClassifier(n_estimators=300, learning_rate=0.05),
    "CatBoost": CatBoostClassifier(iterations=300, learning_rate=0.05, verbose=0)
}

results = {}


for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)
    results[name] = acc

    print("\n==============================")
    print(" Model:", name)
    print("Accuracy:", acc)
    print(classification_report(y_test, pred))


best_model = max(results, key=results.get)

print("\n BEST MODEL:", best_model)
print("Accuracy:", results[best_model])

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier


df = pd.read_excel("/content/dataset.xlsx")


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)

df = df.dropna(subset=["GWP_RR"])

df["Env_Class"] = pd.qcut(
    df["GWP_RR"],
    q=3,
    labels=["Low", "Medium", "High"]
)


X = df.drop(columns=["Env_Class", "CO2_RR", "CH4_RR", "N2O_RR", "GWP_RR"], errors="ignore")
y = df["Env_Class"]


X = X.dropna(axis=1, how="all")


num_cols = X.select_dtypes(include=np.number).columns.tolist()
cat_cols = X.select_dtypes(exclude=np.number).columns.tolist()


num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

X_num = pd.DataFrame(
    num_imputer.fit_transform(X[num_cols]),
    columns=num_cols,
    index=X.index
)

X_cat = pd.DataFrame(
    cat_imputer.fit_transform(X[cat_cols]),
    columns=cat_cols,
    index=X.index
)


X = pd.concat([X_num, X_cat], axis=1)


for col in X.columns:
    if X[col].dtype == "object":
        X[col] = LabelEncoder().fit_transform(X[col].astype(str))


y = LabelEncoder().fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X.values, y, test_size=0.2, random_state=42
)


models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=300, random_state=42),
    "Extra Trees": ExtraTreesClassifier(n_estimators=300, random_state=42),
    "XGBoost": XGBClassifier(n_estimators=300, learning_rate=0.05, eval_metric="mlogloss"),
    "LightGBM": LGBMClassifier(n_estimators=300, learning_rate=0.05),
    "CatBoost": CatBoostClassifier(iterations=300, learning_rate=0.05, verbose=0)
}

results = {}


for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)
    results[name] = acc

    print("\n==============================")
    print("", name)
    print("Accuracy:", acc)
    print(classification_report(y_test, pred))


best_model = max(results, key=results.get)

print("\n BEST MODEL:", best_model)
print("Accuracy:", results[best_model])

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier


df = pd.read_excel("/content/dataset.xlsx")


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


df = df.dropna(subset=["SOC_RR", "TN_RR", "pH_RR", "CEC_RR"])

df["Soil_Health"] = np.where(
    (df["SOC_RR"] > 1) & (df["TN_RR"] > 1) & (df["pH_RR"] > 1) & (df["CEC_RR"] > 1),
    "Healthy",
    np.where(
        (df["SOC_RR"] > 0.8) & (df["TN_RR"] > 0.8),
        "Moderate",
        "Degraded"
    )
)


X = df.drop(columns=["Soil_Health", "SOC_RR", "TN_RR", "pH_RR", "CEC_RR"], errors="ignore")
y = df["Soil_Health"]


X = X.dropna(axis=1, how="all")


num_cols = X.select_dtypes(include=np.number).columns.tolist()
cat_cols = X.select_dtypes(exclude=np.number).columns.tolist()


num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

X_num = pd.DataFrame(
    num_imputer.fit_transform(X[num_cols]),
    columns=num_cols,
    index=X.index
)

X_cat = pd.DataFrame(
    cat_imputer.fit_transform(X[cat_cols]),
    columns=cat_cols,
    index=X.index
)


X = pd.concat([X_num, X_cat], axis=1)


for col in X.columns:
    if X[col].dtype == "object":
        X[col] = LabelEncoder().fit_transform(X[col].astype(str))


y = LabelEncoder().fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X.values, y, test_size=0.2, random_state=42
)


models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=300, random_state=42),
    "Extra Trees": ExtraTreesClassifier(n_estimators=300, random_state=42),
    "XGBoost": XGBClassifier(n_estimators=300, learning_rate=0.05, eval_metric="mlogloss"),
    "LightGBM": LGBMClassifier(n_estimators=300, learning_rate=0.05),
    "CatBoost": CatBoostClassifier(iterations=300, learning_rate=0.05, verbose=0)
}

results = {}


for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)
    results[name] = acc

    print("\n==============================")
    print(" Model:", name)
    print("Accuracy:", acc)
    print(classification_report(y_test, pred))


best_model = max(results, key=results.get)

print("\n BEST MODEL:", best_model)
print("Accuracy:", results[best_model])

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


def convert_ranges(series):
    return series.astype(str).str.replace(
        r'(\d+)-(\d+)',
        lambda m: str((int(m.group(1)) + int(m.group(2))) / 2),
        regex=True
    )

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = convert_ranges(df[col])


def auto_clustering(data, title, features):

    print(f"\n {title}")


    features = [f for f in features if f in data.columns]
    print("Features:", features)

    X = data[features].copy()
    X = X.apply(pd.to_numeric, errors='coerce')
    X = X.fillna(X.median())


    X = X.loc[:, X.nunique() > 1]
    print("Shape:", X.shape)

    if X.shape[1] < 1 or len(X) < 10:
        print(" Not enough data")
        return pd.Series(np.nan, index=data.index)


    X_scaled = StandardScaler().fit_transform(X)


    if X.shape[1] >= 2:
        pca = PCA(n_components=2)
        X_used = pca.fit_transform(X_scaled)
        print(" PCA applied")
    else:
        X_used = X_scaled
        print(" PCA skipped")

    best_score = -1
    best_labels = None
    best_model = ""


    for k in range(2, 7):
        try:
            km = KMeans(n_clusters=k, random_state=42, n_init=10)
            labels = km.fit_predict(X_used)

            if len(set(labels)) > 1:
                score = silhouette_score(X_used, labels)
                print(f"KMeans k={k} → {score:.3f}")

                if score > best_score:
                    best_score = score
                    best_labels = labels
                    best_model = f"KMeans (k={k})"
        except:
            pass


    for k in range(2, 7):
        try:
            agg = AgglomerativeClustering(n_clusters=k)
            labels = agg.fit_predict(X_used)

            if len(set(labels)) > 1:
                score = silhouette_score(X_used, labels)
                print(f"Agglomerative k={k} → {score:.3f}")

                if score > best_score:
                    best_score = score
                    best_labels = labels
                    best_model = f"Agglomerative (k={k})"
        except:
            pass

    for eps in [0.3, 0.5, 0.7]:
        try:
            db = DBSCAN(eps=eps, min_samples=10)
            labels = db.fit_predict(X_used)

            if len(set(labels)) > 1 and -1 not in set(labels):
                score = silhouette_score(X_used, labels)
                print(f"DBSCAN eps={eps} → {score:.3f}")

                if score > best_score:
                    best_score = score
                    best_labels = labels
                    best_model = f"DBSCAN (eps={eps})"
        except:
            pass


    print(f"\n Best Model: {best_model}")
    print(f" Best Silhouette Score: {round(best_score,3)}")

    if X_used.shape[1] >= 2:
        plt.figure(figsize=(6,5))
        sns.scatterplot(x=X_used[:,0], y=X_used[:,1],
                        hue=best_labels, palette="viridis")
        plt.title(f"{title} ({best_model})")
        plt.xlabel("Component 1")
        plt.ylabel("Component 2")
        plt.show()

    return pd.Series(best_labels, index=X.index)


df["Crop_Cluster"] = auto_clustering(
    df,
    "Crop Response Clustering",
    ["CropYield_RR", "SOC_RR", "TN_RR", "GWP_RR"]
)


df["Soil_Cluster"] = auto_clustering(
    df,
    "Soil Clustering",
    ["SOC_initial", "pH_initial", "Clay_initial"]
)


df["Biochar_Cluster"] = auto_clustering(
    df,
    "Biochar Clustering",
    ["C_biochar", "PyrolysisTemperature_biochar", "Ash_biochar"]
)

df["Climate_Cluster"] = auto_clustering(
    df,
    "Climate Clustering",
    ["Temperature", "Precipitation", "WetnessIndex"]
)


plt.figure(figsize=(12,5))

cols = ["Crop_Cluster", "Soil_Cluster", "Biochar_Cluster", "Climate_Cluster"]

for i, col in enumerate(cols):
    plt.subplot(1,4,i+1)
    sns.countplot(x=df[col])
    plt.title(col)

plt.tight_layout()
plt.show()

"""9. clustering"""

def run_clustering(data, title, features):

    features = [f for f in features if f in data.columns]
    features = remove_correlation(data, features)
    print(f"\n {title}")
    print("Features used:", features)

    X = data[features].copy()
    X = X.fillna(X.median(numeric_only=True))


    Q1 = X.quantile(0.25)
    Q3 = X.quantile(0.75)
    IQR = Q3 - Q1
    X = X[~((X < (Q1 - 1.5 * IQR)) | (X > (Q3 + 1.5 * IQR))).any(axis=1)]


    X_scaled = StandardScaler().fit_transform(X)


    pca = PCA(n_components=0.95)
    X_pca = pca.fit_transform(X_scaled)


    best_k, best_score = find_best_k(X_pca)


    kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_pca)

    print("Best K:", best_k)
    print("Silhouette Score:", round(best_score, 3))


    X_vis = PCA(n_components=2).fit_transform(X_pca)

    plt.figure(figsize=(6,5))
    sns.scatterplot(x=X_vis[:,0], y=X_vis[:,1], hue=labels, palette="viridis")
    plt.title(title)
    plt.show()

    return pd.Series(labels, index=X.index)

from sklearn.metrics import silhouette_samples

def plot_silhouette(X_scaled, labels, title):

    sample_silhouette_values = silhouette_samples(X_scaled, labels)

    plt.figure(figsize=(6,5))
    y_lower = 10

    for i in np.unique(labels):
        ith_cluster_values = sample_silhouette_values[labels == i]
        ith_cluster_values.sort()

        size_cluster = ith_cluster_values.shape[0]
        y_upper = y_lower + size_cluster

        plt.fill_betweenx(np.arange(y_lower, y_upper),
                          0, ith_cluster_values)

        y_lower = y_upper + 10

    plt.title(f"Silhouette Plot - {title}")
    plt.xlabel("Silhouette Coefficient")
    plt.ylabel("Cluster")
    plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())


crop_features = ["CropYield_RR", "SOC_RR", "TN_RR", "GWP_RR"]

X_crop = StandardScaler().fit_transform(df[crop_features])
df["Crop_Cluster"] = KMeans(n_clusters=3, random_state=42, n_init=10).fit_predict(X_crop)


soil_features = ["SOC_initial", "pH_initial", "Clay_initial", "Sand_initial", "BD_initial"]

X_soil = StandardScaler().fit_transform(df[soil_features])
df["Soil_Cluster"] = KMeans(n_clusters=3, random_state=42, n_init=10).fit_predict(X_soil)


bio_features = ["pH_biochar", "C_biochar", "PyrolysisTemperature_biochar", "CNRatio_biochar", "Ash_biochar"]

X_bio = StandardScaler().fit_transform(df[bio_features])
df["Biochar_Cluster"] = KMeans(n_clusters=3, random_state=42, n_init=10).fit_predict(X_bio)


crop_effect = df.groupby("Biochar_Cluster")[["CropYield_RR", "SOC_RR"]].mean()

print("\n🌾 BIOCHAR EFFECT ON CROP & SOIL")
print(crop_effect)

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x="SOC_RR",
    y="CropYield_RR",
    hue="Biochar_Cluster",
    palette="viridis",
    s=60
)

plt.title("Biochar Impact: Soil Carbon vs Crop Yield")
plt.xlabel("SOC Improvement (SOC_RR)")
plt.ylabel("Crop Yield Improvement (CropYield_RR)")
plt.show()


plt.figure(figsize=(6,5))

sns.boxplot(
    data=df,
    x="Biochar_Cluster",
    y="SOC_RR",
    palette="Set2"
)

plt.title("Soil Carbon Improvement by Biochar Cluster")
plt.xlabel("Biochar Cluster")
plt.ylabel("SOC Improvement")
plt.show()


all_features = crop_features + soil_features + bio_features

X_all = StandardScaler().fit_transform(df[all_features])
X_pca = PCA(n_components=2).fit_transform(X_all)

plt.figure(figsize=(6,5))

sns.scatterplot(
    x=X_pca[:,0],
    y=X_pca[:,1],
    hue=df["Biochar_Cluster"],
    palette="coolwarm"
)

plt.title("Overall Biochar System Clustering (PCA View)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()


summary = df.groupby("Biochar_Cluster")[[
    "CropYield_RR",
    "SOC_RR",
    "TN_RR",
    "pH_initial"
]].mean()

print("\n FINAL CLUSTER SUMMARY")
print(summary)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(18, 12))


plt.subplot(2, 2, 1)

crop_means = df.groupby("Crop_Cluster")[["CropYield_RR", "SOC_RR", "TN_RR", "GWP_RR"]].mean()

crop_means.plot(kind="bar")
plt.title(" Crop Cluster Positive Impact")
plt.ylabel("Mean Improvement")
plt.xticks(rotation=0)


plt.subplot(2, 2, 2)

soil_means = df.groupby("Soil_Cluster")[["SOC_initial", "pH_initial", "BD_initial"]].mean()

soil_means.plot(kind="bar", colormap="Greens")
plt.title(" Soil Cluster Characteristics")
plt.xticks(rotation=0)


plt.subplot(2, 2, 3)

bio_means = df.groupby("Biochar_Cluster")[["CropYield_RR", "SOC_RR", "TN_RR"]].mean()

bio_means.plot(kind="bar", colormap="Oranges")
plt.title(" Biochar Cluster Positive Effect")
plt.ylabel("Mean Response Ratio")
plt.xticks(rotation=0)


plt.subplot(2, 2, 4)

climate_means = df.groupby("Climate_Cluster")[["Temperature", "Precipitation", "WetnessIndex"]].mean()

climate_means.plot(kind="bar", colormap="coolwarm")
plt.title(" Climate Cluster Patterns")
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

plt.figure(figsize=(18, 12))

crop_means = df.groupby("Crop_Cluster")[["CropYield_RR", "SOC_RR", "TN_RR", "GWP_RR"]].mean()

plt.subplot(2, 2, 1)
crop_means.plot(kind="bar", width=0.8, ax=plt.gca())
plt.title(" Crop Cluster Impact")
plt.ylabel("Mean Response Ratio")
plt.legend(loc="upper right")


soil_means = df.groupby("Soil_Cluster")[["SOC_initial", "pH_initial", "BD_initial"]].mean()

plt.subplot(2, 2, 2)
soil_means.plot(kind="bar", width=0.8, ax=plt.gca())
plt.title(" Soil Cluster Properties")
plt.ylabel("Mean Value")
plt.legend(loc="upper right")


bio_means = df.groupby("Biochar_Cluster")[["CropYield_RR", "SOC_RR", "TN_RR"]].mean()

plt.subplot(2, 2, 3)
bio_means.plot(kind="bar", width=0.8, ax=plt.gca())
plt.title(" Biochar Cluster Effect")
plt.ylabel("Mean Response")
plt.legend(loc="upper right")

climate_means = df.groupby("Climate_Cluster")[["Temperature", "Precipitation", "WetnessIndex"]].mean()

plt.subplot(2, 2, 4)
climate_means.plot(kind="bar", width=0.8, ax=plt.gca())
plt.title(" Climate Cluster Pattern")
plt.ylabel("Mean Value")
plt.legend(loc="upper right")

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.cluster import AgglomerativeClustering, KMeans
from sklearn.metrics import silhouette_score


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())


def advanced_clustering(data, features, title, k=3):

    X = data[features]


    X_scaled = StandardScaler().fit_transform(X)


    X_pca = PCA(n_components=2).fit_transform(X_scaled)

    models = {
        "KMeans": KMeans(n_clusters=k, random_state=42),
        "GMM": GaussianMixture(n_components=k, random_state=42),
        "Hierarchical": AgglomerativeClustering(n_clusters=k)
    }

    results = {}

    plt.figure(figsize=(15,4))

    for i, (name, model) in enumerate(models.items()):

        if name == "GMM":
            labels = model.fit(X_pca).predict(X_pca)
        else:
            labels = model.fit_predict(X_pca)

        score = silhouette_score(X_pca, labels)
        results[name] = score

        plt.subplot(1,3,i+1)
        sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=labels, palette="viridis", s=40)
        plt.title(f"{name} | Silhouette: {score:.2f}")

    plt.suptitle(title)
    plt.show()

    print("\n Model Comparison:")
    for k1, v1 in results.items():
        print(k1, ":", round(v1, 3))

    best_model = max(results, key=results.get)
    print("\n Best Model:", best_model)

    return results



crop_features = ["CropYield_RR", "SOC_RR", "TN_RR", "GWP_RR"]

crop_results = advanced_clustering(df, crop_features, "Crop Response Clustering")


soil_features = ["SOC_initial", "pH_initial", "Clay_initial", "Sand_initial", "BD_initial"]

soil_results = advanced_clustering(df, soil_features, "Soil Health Clustering")

bio_features = ["pH_biochar", "C_biochar", "PyrolysisTemperature_biochar", "CNRatio_biochar", "Ash_biochar"]

bio_results = advanced_clustering(df, bio_features, "Biochar Clustering")

climate_features = ["Temperature", "Precipitation", "WetnessIndex"]

climate_results = advanced_clustering(df, climate_features, "Climate Clustering")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score

sns.set_style("whitegrid")


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)

num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())


def advanced_cluster_visual(data, features, title, k=3):

    X = data[features]


    X_scaled = StandardScaler().fit_transform(X)


    X_pca = PCA(n_components=2).fit_transform(X_scaled)

    models = {
        "KMeans": KMeans(n_clusters=k, random_state=42, n_init=10),
        "GMM": GaussianMixture(n_components=k, random_state=42),
        "Hierarchical": AgglomerativeClustering(n_clusters=k)
    }

    best_score = -1
    best_labels = None
    best_name = ""

    plt.figure(figsize=(15,4))

    for i, (name, model) in enumerate(models.items()):

        if name == "GMM":
            labels = model.fit(X_pca).predict(X_pca)
        else:
            labels = model.fit_predict(X_pca)

        score = silhouette_score(X_pca, labels)

        if score > best_score:
            best_score = score
            best_labels = labels
            best_name = name

        # visualization per model
        plt.subplot(1,3,i+1)
        sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=labels, palette="viridis", s=40)
        plt.title(f"{name} | Silhouette={score:.2f}")

    plt.suptitle(title)
    plt.show()

    print(f"\n Best Model for {title}: {best_name} | Score: {best_score:.3f}")


    plt.figure(figsize=(6,5))
    sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=best_labels, palette="coolwarm", s=50)
    plt.title(f"FINAL CLUSTERS - {title}")
    plt.show()

    return best_labels



df["Crop_Cluster"] = advanced_cluster_visual(
    df,
    ["CropYield_RR", "SOC_RR", "TN_RR", "GWP_RR"],
    "Crop Yield System Clustering",
    k=3
)


df["Soil_Cluster"] = advanced_cluster_visual(
    df,
    ["SOC_initial", "pH_initial", "Clay_initial", "Sand_initial", "BD_initial"],
    "Soil Health Clustering",
    k=3
)


df["Biochar_Cluster"] = advanced_cluster_visual(
    df,
    ["pH_biochar", "C_biochar", "PyrolysisTemperature_biochar", "CNRatio_biochar", "Ash_biochar"],
    "Biochar Property Clustering",
    k=3
)


df["Climate_Cluster"] = advanced_cluster_visual(
    df,
    ["Temperature", "Precipitation", "WetnessIndex"],
    "Climate System Clustering",
    k=3
)


plt.figure(figsize=(12,5))

for i, col in enumerate(["Crop_Cluster","Soil_Cluster","Biochar_Cluster","Climate_Cluster"]):
    plt.subplot(1,4,i+1)
    sns.countplot(x=df[col], palette="Set2")
    plt.title(col)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

plt.figure(figsize=(16, 12))


plt.subplot(2, 2, 1)

crop_mean = df.groupby("Crop_Cluster")[["CropYield_RR", "SOC_RR", "TN_RR", "GWP_RR"]].mean()

crop_mean.plot(kind="bar", ax=plt.gca(), width=0.8)
plt.title("Crop Cluster Comparison")
plt.ylabel("Mean Response Ratio")
plt.xticks(rotation=0)
plt.legend(loc="best")


plt.subplot(2, 2, 2)

soil_mean = df.groupby("Soil_Cluster")[["SOC_initial", "pH_initial", "BD_initial"]].mean()

soil_mean.plot(kind="bar", ax=plt.gca(), width=0.8, colormap="Greens")
plt.title(" Soil Cluster Comparison")
plt.ylabel("Mean Soil Properties")
plt.xticks(rotation=0)
plt.legend(loc="best")


plt.subplot(2, 2, 3)

bio_mean = df.groupby("Biochar_Cluster")[["CropYield_RR", "SOC_RR", "TN_RR"]].mean()

bio_mean.plot(kind="bar", ax=plt.gca(), width=0.8, colormap="Oranges")
plt.title("🔥 Biochar Cluster Impact")
plt.ylabel("Mean Response Ratio")
plt.xticks(rotation=0)
plt.legend(loc="best")


plt.subplot(2, 2, 4)

climate_mean = df.groupby("Climate_Cluster")[["Temperature", "Precipitation", "WetnessIndex"]].mean()

climate_mean.plot(kind="bar", ax=plt.gca(), width=0.8, colormap="coolwarm")
plt.title(" Climate Cluster Comparison")
plt.ylabel("Mean Value")
plt.xticks(rotation=0)
plt.legend(loc="best")

plt.tight_layout()
plt.show()

import pandas as pd


crop_score = df.groupby("Crop_Cluster")[["CropYield_RR", "SOC_RR", "GWP_RR"]].mean()

crop_label = {}

for c in crop_score.index:
    if (crop_score.loc[c, "CropYield_RR"] > 1) and (crop_score.loc[c, "SOC_RR"] > 1) and (crop_score.loc[c, "GWP_RR"] < 1):
        crop_label[c] = "GOOD "
    elif (crop_score.loc[c, "CropYield_RR"] < 1) or (crop_score.loc[c, "GWP_RR"] > 1):
        crop_label[c] = "BAD "
    else:
        crop_label[c] = "MODERATE "

df["Crop_Cluster_Label"] = df["Crop_Cluster"].map(crop_label)

print("🌾 Crop Cluster Labels:")
print(crop_label)


soil_score = df.groupby("Soil_Cluster")[["SOC_initial", "pH_initial", "BD_initial"]].mean()

soil_label = {}

for c in soil_score.index:
    if (soil_score.loc[c, "SOC_initial"] > df["SOC_initial"].median()) and (soil_score.loc[c, "BD_initial"] < df["BD_initial"].median()):
        soil_label[c] = "GOOD "
    else:
        soil_label[c] = "BAD "

df["Soil_Cluster_Label"] = df["Soil_Cluster"].map(soil_label)

print("\n Soil Cluster Labels:")
print(soil_label)


bio_score = df.groupby("Biochar_Cluster")[["CropYield_RR", "SOC_RR", "TN_RR"]].mean()

bio_label = {}

for c in bio_score.index:
    if (bio_score.loc[c, "CropYield_RR"] > 1) and (bio_score.loc[c, "SOC_RR"] > 1):
        bio_label[c] = "GOOD "
    elif (bio_score.loc[c, "CropYield_RR"] < 1):
        bio_label[c] = "BAD "
    else:
        bio_label[c] = "MODERATE "

df["Biochar_Cluster_Label"] = df["Biochar_Cluster"].map(bio_label)

print("\n Biochar Cluster Labels:")
print(bio_label)

climate_score = df.groupby("Climate_Cluster")[["Temperature", "Precipitation", "WetnessIndex"]].mean()

climate_label = {}

for c in climate_score.index:
    if climate_score.loc[c, "WetnessIndex"] > df["WetnessIndex"].median():
        climate_label[c] = "GOOD "
    else:
        climate_label[c] = "BAD "

df["Climate_Cluster_Label"] = df["Climate_Cluster"].map(climate_label)

print("\n Climate Cluster Labels:")
print(climate_label)

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)

num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())


metrics = [
    "CropYield_T", "CropYield_CK",
    "SOC_RR", "TN_RR",
    "CO2_RR", "CH4_RR", "N2O_RR",
    "GWP_RR", "GHGI_RR"
]

metrics = [m for m in metrics if m in df.columns]

biochar_score = df.groupby("Type_biochar")[metrics].mean()


biochar_score["Yield_Improvement"] = biochar_score.get("CropYield_T", 0) / (biochar_score.get("CropYield_CK", 1) + 1e-6)

biochar_score["Soil_Benefit"] = biochar_score.get("SOC_RR", 0) + biochar_score.get("TN_RR", 0)

biochar_score["Emission_Reduction"] = (
    -biochar_score.get("CO2_RR", 0)
    -biochar_score.get("CH4_RR", 0)
    -biochar_score.get("N2O_RR", 0)
)

biochar_score["Climate_Benefit"] = (
    -biochar_score.get("GWP_RR", 0)
    -biochar_score.get("GHGI_RR", 0)
)


biochar_score["Final_Score"] = (
    0.4 * biochar_score["Yield_Improvement"] +
    0.3 * biochar_score["Soil_Benefit"] +
    0.2 * biochar_score["Emission_Reduction"] +
    0.1 * biochar_score["Climate_Benefit"]
)


top_biochar = biochar_score.sort_values("Final_Score", ascending=False).head(10)

print("\n TOP BIOCHAR TYPES (BEST TO WORST)")
print(top_biochar[["Final_Score"]])


plt.figure(figsize=(10,5))

top_biochar["Final_Score"].plot(kind="bar", color="green")

plt.title(" Top Biochar Types Based on Yield + Soil + Climate Impact")
plt.ylabel("Composite Performance Score")
plt.xlabel("Biochar Type")
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], pd.NA)

num_cols = df.select_dtypes(include="number").columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())


yield_metrics = ["CropYield_T", "CropYield_CK"]
soil_metrics = ["SOC_RR", "TN_RR"]
emission_metrics = ["CO2_RR", "CH4_RR", "N2O_RR"]
climate_metrics = ["GWP_RR", "GHGI_RR"]

all_metrics = {
    "Yield": yield_metrics,
    "Soil": soil_metrics,
    "Emissions": emission_metrics,
    "Climate": climate_metrics
}


best_results = {}

for group, metrics in all_metrics.items():

    metrics = [m for m in metrics if m in df.columns]

    temp = df.groupby("Type_biochar")[metrics].mean()

    # define score direction (important!)
    score = temp.copy()

    for col in score.columns:
        # lower is better for emissions & climate
        if "CO2" in col or "CH4" in col or "N2O" in col or "GWP" in col or "GHGI" in col:
            score[col] = -score[col]

    score["Final_Score"] = score.mean(axis=1)

    best = score["Final_Score"].idxmax()
    best_results[group] = best

    print(f"\n BEST BIOCHAR for {group}: {best}")


plt.figure(figsize=(10,5))

sns.barplot(
    x=list(best_results.keys()),
    y=[1]*len(best_results),
    hue=list(best_results.values())
)

plt.title(" Best Biochar Type per Metric Category")
plt.ylabel("")
plt.yticks([])
plt.xlabel("Metric Category")
plt.legend(title="Best Biochar", bbox_to_anchor=(1.05,1))
plt.tight_layout()
plt.show()

import pandas as pd


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], pd.NA)

num_cols = df.select_dtypes(include="number").columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())


grouped = df.groupby("Type_biochar")[[
    "CropYield_T",
    "CropYield_CK",
    "SOC_RR",
    "TN_RR",
    "CO2_RR",
    "CH4_RR",
    "N2O_RR",
    "GWP_RR",
    "GHGI_RR"
]].mean()



score = pd.DataFrame(index=grouped.index)


score["Yield"] = grouped["CropYield_T"] / (grouped["CropYield_CK"] + 1e-6)


score["Soil"] = grouped["SOC_RR"] + grouped["TN_RR"]


score["Emissions"] = -(grouped["CO2_RR"] + grouped["CH4_RR"] + grouped["N2O_RR"])


score["Climate"] = -(grouped["GWP_RR"] + grouped["GHGI_RR"])


score["Final_Score"] = (
    0.4 * score["Yield"] +
    0.3 * score["Soil"] +
    0.2 * score["Emissions"] +
    0.1 * score["Climate"]
)


best_biochar = score.sort_values("Final_Score", ascending=False)

print("\n BEST BIOCHAR TYPES (RANKED)")
print(best_biochar["Final_Score"])

print("\n TOP BIOCHAR:")
print(best_biochar.index[0])

import pandas as pd

df.columns = df.columns.str.strip().str.replace(" ", "_")


g = df.groupby("Type_biochar").mean(numeric_only=True)


best_yield = g["CropYield_T"].idxmax()


soil_score = g[["SOC_RR", "TN_RR"]].sum(axis=1)
best_soil = soil_score.idxmax()


emission_cols = [c for c in ["CO2_RR","CH4_RR","N2O_RR"] if c in g.columns]
emission_score = -g[emission_cols].sum(axis=1)
best_emission = emission_score.idxmax()


climate_cols = [c for c in ["GWP","GHGI","GWP_RR","GHGI_RR"] if c in g.columns]
climate_score = -g[climate_cols].sum(axis=1)
best_climate = climate_score.idxmax()


print(" Best Yield Biochar:", best_yield)
print(" Best Soil Biochar:", best_soil)
print(" Best Emission Biochar:", best_emission)
print(" Best Climate Biochar:", best_climate)





g["Final_Score"] = (
    0.4 * g["CropYield_T"] +
    0.3 * (g.get("SOC_RR",0) + g.get("TN_RR",0)) +
    0.2 * (-(g.get("CO2_RR",0) + g.get("CH4_RR",0) + g.get("N2O_RR",0))) +
    0.1 * (-(g.get("GWP_RR",0) + g.get("GHGI_RR",0)))
)

best_overall = g["Final_Score"].idxmax()

print("\n OVERALL BEST BIOCHAR:", best_overall)

import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


targets = ["CropYield_T", "SOC_RR", "GWP_RR"]
targets = [t for t in targets if t in df.columns]

X = df.drop(columns=targets)
y = df[targets]

for col in X.columns:
    if X[col].dtype == "object":
        X[col] = X[col].astype(str)

X = X.replace(["nan", "None", "NaN", ""], np.nan)

num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns


num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])


X_processed = preprocessor.fit_transform(X)

if hasattr(X_processed, "toarray"):
    X_processed = X_processed.toarray()


y = SimpleImputer(strategy="median").fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, random_state=42
)


model = tf.keras.Sequential([
    tf.keras.layers.Dense(256, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(y.shape[1])
])

model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)


history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    batch_size=32,
    verbose=1
)



y_pred = model.predict(X_test)


print("\n MODEL PERFORMANCE\n")

targets_used = ["CropYield_T", "SOC_RR", "GWP_RR"][:y.shape[1]]

for i, t in enumerate(targets_used):
    print("\n🔹", t)
    print("R2 Score :", r2_score(y_test[:, i], y_pred[:, i]))
    print("RMSE     :", np.sqrt(mean_squared_error(y_test[:, i], y_pred[:, i])))
    print("MAE      :", mean_absolute_error(y_test[:, i], y_pred[:, i]))

import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


df["Yield_Class"] = (df["CropYield_T"] > df["CropYield_T"].median()).astype(int)

X = df.drop(columns=["Yield_Class", "CropYield_T"])
y = df["Yield_Class"]

for col in X.columns:
    if X[col].dtype == "object":
        X[col] = X[col].astype(str)

X = X.replace(["nan", "None", "NaN", ""], np.nan)

num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns


num_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols)
])

X_processed = preprocessor.fit_transform(X)
if hasattr(X_processed, "toarray"):
    X_processed = X_processed.toarray()


X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, random_state=42
)


model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)


model.fit(X_train, y_train, epochs=30, batch_size=32, verbose=1)


y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)


print("\n Accuracy:", accuracy_score(y_test, y_pred))
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\n Report:\n", classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

plt.plot(model.history.history["accuracy"], label="train")
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

from sklearn.metrics import roc_curve, auc

fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    r2_score, mean_squared_error, mean_absolute_error,
    accuracy_score, confusion_matrix, roc_curve, auc
)


df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.replace([np.inf, -np.inf], np.nan)


df["Yield_Class"] = (df["CropYield_T"] > df["CropYield_T"].median()).astype(int)


targets_reg = ["CropYield_T"]
target_clf = "Yield_Class"

X = df.drop(columns=[target_clf, "CropYield_T"])
y_reg = df[targets_reg]
y_clf = df[target_clf]


for col in X.columns:
    if X[col].dtype == "object":
        X[col] = X[col].astype(str)

X = X.replace(["nan", "None", "NaN", ""], np.nan)

# =========================================================
# 5. SPLIT COLUMN TYPES
# =========================================================
num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(exclude=np.number).columns

# =========================================================
# 6. PREPROCESSING
# =========================================================
num_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols)
])

X_processed = preprocessor.fit_transform(X)
if hasattr(X_processed, "toarray"):
    X_processed = X_processed.toarray()

# =========================================================
# 7. TARGET CLEAN
# =========================================================
y_reg = SimpleImputer(strategy="median").fit_transform(y_reg)

# =========================================================
# 8. TRAIN TEST SPLIT
# =========================================================
X_train, X_test, y_train_reg, y_test_reg = train_test_split(
    X_processed, y_reg, test_size=0.2, random_state=42
)

_, _, y_train_clf, y_test_clf = train_test_split(
    X_processed, y_clf, test_size=0.2, random_state=42
)

# =========================================================
# 9. REGRESSION MODEL
# =========================================================
reg_model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(1)
])

reg_model.compile(optimizer="adam", loss="mse")

history_reg = reg_model.fit(
    X_train, y_train_reg,
    validation_data=(X_test, y_test_reg),
    epochs=30, batch_size=32, verbose=0
)

y_pred_reg = reg_model.predict(X_test)

# =========================================================
# 10. CLASSIFICATION MODEL
# =========================================================
clf_model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

clf_model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

history_clf = clf_model.fit(
    X_train, y_train_clf,
    epochs=30, batch_size=32, verbose=0
)

y_pred_prob = clf_model.predict(X_test)
y_pred_clf = (y_pred_prob > 0.5).astype(int)

# =========================================================
# 11. EVALUATION
# =========================================================
print("\n📊 REGRESSION RESULTS")
print("R2 :", r2_score(y_test_reg, y_pred_reg))
print("RMSE :", np.sqrt(mean_squared_error(y_test_reg, y_pred_reg)))

print("\n🎯 CLASSIFICATION RESULTS")
print("Accuracy :", accuracy_score(y_test_clf, y_pred_clf))
print("Confusion Matrix:\n", confusion_matrix(y_test_clf, y_pred_clf))

# =========================================================
# 12. VISUALIZATIONS
# =========================================================

# 🔹 Loss Curve
plt.figure()
plt.plot(history_reg.history['loss'], label='Train Loss')
plt.plot(history_reg.history['val_loss'], label='Val Loss')
plt.title("Loss Curve")
plt.legend()
plt.show()


plt.figure()
plt.scatter(y_test_reg, y_pred_reg, alpha=0.5)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")
plt.show()

residuals = y_test_reg.flatten() - y_pred_reg.flatten()
plt.figure()
plt.scatter(y_pred_reg, residuals, alpha=0.5)
plt.axhline(0, linestyle='--')
plt.title("Residual Plot")
plt.show()


sns.heatmap(confusion_matrix(y_test_clf, y_pred_clf), annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.show()


fpr, tpr, _ = roc_curve(y_test_clf, y_pred_prob)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC={roc_auc:.2f}")
plt.plot([0,1],[0,1],'--')
plt.title("ROC Curve")
plt.legend()
plt.show()

!pip install pandas scikit-learn openpyxl


import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


df = pd.read_excel("/content/dataset.xlsx")



df.columns = df.columns.str.strip().str.replace(" ", "_")


df = df.replace([np.inf, -np.inf], np.nan)


cols = [
    "CropType", "ClimateZone", "SoilDepth",
    "CropYield_T", "CropYield_CK", "CropYield_RR",
    "SOC_RR", "TN_RR", "DOC_RR", "pH_RR",
    "CO2_RR", "CH4_RR", "N2O_RR",
    "GWP_RR", "GHGI_RR",
    "BiocharAddition", "PyrolysisTemperature_biochar"
]

df = df[cols].copy()


df = df.fillna("unknown")


def row_to_text(row):
    return (
        f"crop {row['CropType']} "
        f"climate {row['ClimateZone']} "
        f"soil {row['SoilDepth']} "
        f"biochar {row['BiocharAddition']} "
        f"temperature {row['PyrolysisTemperature_biochar']} "
        f"yield effect soil improvement emission reduction sustainability"
    )

df["text"] = df.apply(row_to_text, axis=1)


print(" Sample text data:\n", df["text"].head())


vectorizer = TfidfVectorizer(stop_words=None)
X = vectorizer.fit_transform(df["text"].astype(str))

print(" TF-IDF Shape:", X.shape)


def retrieve(query, top_k=5):
    query_vec = vectorizer.transform([query])
    similarity = cosine_similarity(query_vec, X).flatten()
    indices = similarity.argsort()[-top_k:][::-1]
    return df.iloc[indices]


def generate_answer(query, data):


    for col in ["CropYield_RR", "SOC_RR", "CO2_RR", "CH4_RR", "N2O_RR", "GWP_RR"]:
        data[col] = pd.to_numeric(data[col], errors="coerce")

    ans = "\n DATA-DRIVEN BIOCHAR INSIGHTS\n\n"


    yield_avg = data["CropYield_RR"].mean()
    soc_avg = data["SOC_RR"].mean()
    ghg_avg = data[["CO2_RR","CH4_RR","N2O_RR"]].mean().mean()
    gwp_avg = data["GWP_RR"].mean()

    ans += f" Yield Response: {yield_avg:.2f}\n"
    ans += f" Soil Improvement (SOC): {soc_avg:.2f}\n"
    ans += f" Emission Impact: {ghg_avg:.2f}\n"
    ans += f" GWP Impact: {gwp_avg:.2f}\n\n"

    # Interpretation
    ans += " INTERPRETATION:\n"

    if yield_avg > 1:
        ans += " Biochar improves crop yield\n"
    else:
        ans += " Limited yield improvement\n"

    if soc_avg > 1:
        ans += " Soil quality improved\n"
    else:
        ans += " Soil improvement low\n"

    if ghg_avg < 1:
        ans += " Reduces greenhouse gases\n"
    else:
        ans += " Emission reduction weak\n"

    if gwp_avg < 1:
        ans += " Climate friendly (low GWP)\n"
    else:
        ans += " High climate impact\n"


    if not data["CropYield_RR"].isna().all():
        best = data.loc[data["CropYield_RR"].idxmax()]
        ans += "\n BEST CONDITION FOUND:\n"
        ans += f"Crop: {best['CropType']}\n"
        ans += f"Climate: {best['ClimateZone']}\n"
        ans += f"Biochar: {best['BiocharAddition']}\n"
        ans += f"Yield RR: {best['CropYield_RR']}\n"

    return ans


print("\n BIOCHAR GENAI CHATBOT READY (OFFLINE)\n")

while True:
    query = input(" Ask your question (or 'exit'): ")

    if query.lower() == "exit":
        print(" Exiting chatbot...")
        break

    retrieved_data = retrieve(query)
    response = generate_answer(query, retrieved_data)

    print(response)

!pip install pandas scikit-learn openpyxl


import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


df = pd.read_excel("/content/dataset.xlsx")

df.columns = df.columns.str.strip().str.replace(" ", "_")


df = df.replace([np.inf, -np.inf], np.nan)


cols = [
    "CropType", "ClimateZone", "SoilDepth",
    "CropYield_T", "CropYield_CK", "CropYield_RR",
    "SOC_RR", "TN_RR", "DOC_RR", "pH_RR",
    "CO2_RR", "CH4_RR", "N2O_RR",
    "GWP_RR", "GHGI_RR",
    "BiocharAddition", "PyrolysisTemperature_biochar"
]

df = df[cols].copy()


df = df.fillna("unknown")


def row_to_text(row):
    return (
        f"crop {row['CropType']} "
        f"climate {row['ClimateZone']} "
        f"soil_depth {row['SoilDepth']} "
        f"biochar {row['BiocharAddition']} "
        f"temp {row['PyrolysisTemperature_biochar']} "
        f"yield_rr {row['CropYield_RR']} "
        f"soc_rr {row['SOC_RR']} "
        f"co2 {row['CO2_RR']} "
        f"ch4 {row['CH4_RR']} "
        f"n2o {row['N2O_RR']} "
        f"gwp {row['GWP_RR']}"
    )

df["text"] = df.apply(row_to_text, axis=1)

print(" Sample text:\n", df["text"].head())


vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["text"].astype(str))

print(" TF-IDF Shape:", X.shape)


def retrieve(query, top_k=5):
    query_vec = vectorizer.transform([query])
    similarity = cosine_similarity(query_vec, X).flatten()
    indices = similarity.argsort()[-top_k:][::-1]
    return df.iloc[indices]


def generate_answer(query, data):

    data = data.copy()


    for col in ["CropYield_RR", "SOC_RR", "CO2_RR", "CH4_RR", "N2O_RR", "GWP_RR"]:
        data.loc[:, col] = pd.to_numeric(data[col], errors="coerce")

    query = query.lower()
    ans = "\n DATA-DRIVEN BIOCHAR INSIGHTS\n\n"


    if "gwp" in query or "global warming" in query:
        gwp_avg = data["GWP_RR"].mean()

        ans += f" Average GWP Response: {gwp_avg:.2f}\n\n"

        if gwp_avg < 1:
            ans += " Biochar REDUCES global warming potential\n"
        else:
            ans += " Biochar does NOT significantly reduce GWP\n"

        return ans


    elif "yield" in query:
        yield_avg = data["CropYield_RR"].mean()

        ans += f" Yield Response: {yield_avg:.2f}\n\n"

        if yield_avg > 1:
            ans += " Biochar improves crop yield\n"
        else:
            ans += " Limited yield improvement\n"

        return ans


    elif "soil" in query or "soc" in query:
        soc_avg = data["SOC_RR"].mean()

        ans += f" Soil Organic Carbon (SOC): {soc_avg:.2f}\n\n"

        if soc_avg > 1:
            ans += " Soil quality improved\n"
        else:
            ans += " Weak soil improvement\n"

        return ans


    else:
        yield_avg = data["CropYield_RR"].mean()
        soc_avg = data["SOC_RR"].mean()
        ghg_avg = data[["CO2_RR","CH4_RR","N2O_RR"]].mean().mean()
        gwp_avg = data["GWP_RR"].mean()

        ans += f"Yield: {yield_avg:.2f}\n"
        ans += f" SOC: {soc_avg:.2f}\n"
        ans += f" Emissions: {ghg_avg:.2f}\n"
        ans += f" GWP: {gwp_avg:.2f}\n\n"


        ans += " INTERPRETATION:\n"

        if yield_avg > 1:
            ans += " Improves crop yield\n"
        else:
            ans += " Low yield impact\n"

        if soc_avg > 1:
            ans += " Improves soil health\n"
        else:
            ans += "Weak soil improvement\n"

        if gwp_avg < 1:
            ans += " Climate friendly\n"
        else:
            ans += " Higher climate impact\n"


        if not data["CropYield_RR"].isna().all():
            best = data.loc[data["CropYield_RR"].idxmax()]
            ans += "\n BEST CONDITION:\n"
            ans += f"Crop: {best['CropType']}\n"
            ans += f"Climate: {best['ClimateZone']}\n"
            ans += f"Biochar: {best['BiocharAddition']}\n"
            ans += f"Yield RR: {best['CropYield_RR']}\n"

        return ans


print("\n BIOCHAR GENAI CHATBOT READY (OFFLINE)\n")

while True:
    query = input(" Ask your question (or 'exit'): ")

    if query.lower() == "exit":
        print(" Exiting chatbot...")
        break

    retrieved_data = retrieve(query)
    response = generate_answer(query, retrieved_data)

    print(response)

def generate_graph(query, data):

    query = query.lower()

    numeric_cols = [
        "CropYield_T","CropYield_CK","CropYield_RR",
        "SOC_RR","TN_RR","CO2_RR","CH4_RR","N2O_RR","GWP_RR"
    ]

    for col in numeric_cols:
        if col in data.columns:
            data[col] = pd.to_numeric(data[col], errors='coerce')


    if "yield" in query and "compare" in query:
        plt.figure()
        data[["CropYield_T","CropYield_CK"]].mean().plot(kind='bar')
        plt.title("Yield Comparison: Treatment vs Control")
        plt.show()
        return "📊 Showing yield comparison graph"


    elif "response" in query or "rr" in query:
        cols = ["SOC_RR","TN_RR","CO2_RR","CH4_RR","N2O_RR","GWP_RR"]
        cols = [c for c in cols if c in data.columns]

        plt.figure()
        data[cols].mean().plot(kind='bar')
        plt.title("Response Ratio Comparison")
        plt.show()
        return " Showing response ratio graph"


    elif "top" in query or "best" in query:
        if "CropYield_RR" in data.columns:
            top = data.sort_values("CropYield_RR", ascending=False).head(10)

            plt.figure()
            plt.barh(top["CropType"].astype(str), top["CropYield_RR"])
            plt.title("Top Biochar for Yield")
            plt.gca().invert_yaxis()
            plt.show()

            return " Showing top biochar graph"


    elif "correlation" in query:
        cols = ["CropYield_RR","SOC_RR","TN_RR","CO2_RR","N2O_RR","GWP_RR"]
        cols = [c for c in cols if c in data.columns]

        plt.figure()
        sns.heatmap(data[cols].corr(), annot=True, cmap="coolwarm")
        plt.title("Correlation Matrix")
        plt.show()

        return " Showing correlation heatmap"


    elif "trade" in query or "gwp" in query:
        plt.figure()
        plt.scatter(data["CropYield_RR"], data["GWP_RR"])
        plt.xlabel("Yield RR")
        plt.ylabel("GWP RR")
        plt.title("Yield vs Climate Impact")
        plt.show()

        return " Showing yield vs GWP trade-off"

    return None

!pip install streamlit pandas scikit-learn openpyxl


import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title(" Biochar GenAI Web App")


uploaded_file = st.file_uploader("Upload your dataset", type=["xlsx"])

if uploaded_file:
    df = pd.read_excel(uploaded_file)

    st.write(" Dataset Preview")
    st.dataframe(df.head())


    if "CropType" in df.columns:
        crop = st.selectbox("Select Crop", df["CropType"].dropna().unique())
        df_crop = df[df["CropType"] == crop]


        if "CropYield_T" in df.columns and "CropYield_CK" in df.columns:
            st.write(" Yield Comparison")

            df_crop["CropYield_T"] = pd.to_numeric(df_crop["CropYield_T"], errors='coerce')
            df_crop["CropYield_CK"] = pd.to_numeric(df_crop["CropYield_CK"], errors='coerce')

            fig, ax = plt.subplots()
            df_crop[["CropYield_T","CropYield_CK"]].mean().plot(kind='bar', ax=ax)
            st.pyplot(fig)


    query = st.text_input("Ask a question")

    if query:
        st.write("Answer")

        if "yield" in query.lower():
            st.write("Biochar improves yield based on dataset trends.")
        elif "emission" in query.lower():
            st.write("Biochar reduces greenhouse gas emissions.")
        else:
            st.write("Insight generated from dataset.")